### PR TITLE
Fix dash shell support

### LINKED ISSUE #39: Fix dash support issues
Shellcheck generated Dash issues that we should fix for dash shell implementations

```
In ./falcon-linux-deploy.sh line 43:
        cs_falcon_args+=" $cs_token"
        ^------------^ SC3024 (error): In dash, += is not supported.


In ./falcon-linux-deploy.sh line 91:
        sensor_versions+=("$i")
        ^-------------^ SC3024 (error): In dash, += is not supported.
                         ^----^ SC3030 (error): In dash, arrays are not supported.


In ./falcon-linux-deploy.sh line 94:
    if [[ "${#sensor_versions[@]}" -gt 1 ]]; then
       ^-- SC3010 (error): In dash, [[ ]] is not supported.


In ./falcon-linux-deploy.sh line 96:
            echo "${sensor_versions[1]}"
                  ^-------------------^ SC3054 (error): In dash, array references are not supported.


In ./falcon-linux-deploy.sh line 98:
            echo "${sensor_versions[0]}"
                  ^-------------------^ SC3054 (error): In dash, array references are not supported.


In ./falcon-linux-deploy.sh line 101:
        echo "${sensor_versions[0]}"
              ^-------------------^ SC3054 (error): In dash, array references are not supported.


In ./falcon-linux-deploy.sh line 113:
        if [[ $exit_status -ne 0 ]]; then
           ^----------------------^ SC3010 (error): In dash, [[ ]] is not supported.


In ./falcon-linux-deploy.sh line 116:
        if [[ $cs_falcon_sensor_version_dec -gt 0 ]]; then
           ^-- SC3010 (error): In dash, [[ ]] is not supported.


In ./falcon-linux-deploy.sh line 413:
       if ! [[ $FALCON_SENSOR_VERSION_DECREMENT =~ $re ]]; then
            ^-- SC3010 (error): In dash, [[ ]] is not supported.


In ./falcon-linux-deploy.sh line 415:
       elif ! [[ $FALCON_SENSOR_VERSION_DECREMENT -ge 0 && $FALCON_SENSOR_VERSION_DECREMENT -le 5 ]]; then
              ^-- SC3010 (error): In dash, [[ ]] is not supported.


In ./falcon-linux-deploy.sh line 428:
    if ! command -v curl &> /dev/null; then
                         ^----------^ SC3020 (error): In dash, &> is not supported.

For more information:
  https://www.shellcheck.net/wiki/SC3010 -- In dash, [[ ]] is not supported.
  https://www.shellcheck.net/wiki/SC3020 -- In dash, &> is not supported.
  https://www.shellcheck.net/wiki/SC3024 -- In dash, += is not supported.
```

### PR DESCRIPTION
**Pull request by redhatrises**
- Fixes #39

### CODE REVIEW

File: falcon-linux-deploy.sh [hunk 1]
```diff
@@ -86,20 +86,20 @@ cs_sensor_policy_version() {
...
+            echo "$2"
         else
-            echo "${sensor_versions[0]}"
+            echo "$1"
         fi
     else
-        echo "${sensor_versions[0]}"
+        echo "$1"
     fi
+    IFS=$oldIFS
```
Comment (isimluk) [inline falcon-linux-deploy.sh:102]: 🙏 I hope you tested this in various settings.

The code read good, but I am little hesitant to touch this part of the code. :-)

**Review by isimluk — APPROVED** [review]

File: falcon-linux-deploy.sh (hunk 1 above)
Comment (redhatrises) [reply falcon-linux-deploy.sh:102]: Tested on centos 8, amazon linux arm64, and ubuntu.

Comment (isimluk) [reply falcon-linux-deploy.sh:102]: Thank You!
